export const LOAD_CHARACTERS_SUCCESS = "LOAD_CHARACTERS_SUCCESS";
export const LOAD_CHARACTERS_FAIL = "LOAD_CHARACTERS_FAIL";
export const LOAD_MOVIE_DETAILS_SUCCESS = "LOAD_MOVIE_DETAILS_SUCCESS";
export const LOAD_MOVIE_DETAILS_FAIL = "LOAD_MOVIE_DETAILS_FAIL";
